# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Vungle Sample App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Vungle Sample App
  pod 'Vungle-Advanced-Auction-SDK'

  target 'Vungle Sample AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
